[package]
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "rstopo"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "simplex",
    "std",
]

full = [
    "default",
    "rand",
    "serde",
]

# ********* [FF] Features *********
simplex = [
    "dep:rstopo-simplex",
]

# [FF] Dependencies
alloc = [
    "rstopo-core/alloc",
    "rstopo-simplex?/alloc",
]

rand = [
    "rstopo-core/rand",
    "rstopo-simplex?/rand",
]

serde = [
    "rstopo-core/serde",
    "rstopo-simplex?/serde",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "rstopo-core/std",
    "rstopo-simplex?/std",
]

wasm = [
    "rstopo-core/wasm",
    "rstopo-simplex?/wasm",
]

wasi = [
    "rstopo-core/wasi",
    "rstopo-simplex?/wasi",
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = false
test = true

[dependencies.rstopo-core]
default-features = false
path = "../core"
version = "0.0.1"

[dependencies.rstopo-simplex]
default-features = false
optional = true
path = "../simplex"
version = "0.0.1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
